jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Set up Chrome and WebDriver
      - name: Set up Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome
          chrome --version
          chromedriver --version

      # Python setup
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      # Run scraper with headless Chrome
      - name: Run scraper
        run: |
          python scraper/scraper.py